/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.programacion.proyectofinal.views;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author elava
 */
public class info extends javax.swing.JPanel {

    public info() {
        initComponents();
        intComponents();

    }

    public void intComponents() {
        txtArea.setBackground(Color.white);
        //txtArea.setForeground(Color.black);
        lbl1.setBackground(Color.white);
        lbl2.setBackground(Color.white);
        lbl3.setBackground(Color.white);
        lbl4.setBackground(Color.white);
        lbl5.setBackground(Color.white);
        lbl1.setForeground(Color.black);
        lbl2.setForeground(Color.black);
        lbl3.setForeground(Color.black);
        lbl4.setForeground(Color.black);
        lbl5.setForeground(Color.black);
        lbl7.setForeground(Color.black);

        //txt1.setForeground(Color.GRAY);
        // txt2.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        lbl5 = new javax.swing.JTextField();
        lbl1 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\elava\\Documents\\NetBeansProjects\\programacion-proyectofinal\\src\\main\\Others resource\\img\\rafiki.png")); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\elava\\Documents\\NetBeansProjects\\programacion-proyectofinal\\src\\main\\Others resource\\img\\rafiki.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 180, 250));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtArea.setRows(5);
        txtArea.setText("\nNoteApp es un  gestor de tareas diseñado para maximizar la eficiencia  y la \norganización tanto personal como empresarial. Permite  a los usuarios  \nregistrar y gestionar tareas asignando colores que indican diferentes niveles de \nprioridad. Las tareas urgentes se destacan en rojo, señalando plazos inminentes y \nresponsabilidades críticas.  Las tareas de importancia moderada se marcan \nen amarillo, indicando que requieren atención en el futuro cercano. Por último, \nlas tareas menos urgentes se representan en verde, facilitando una planificación \nmás flexible.\n\n\n\n\n");
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 230));

        lbl5.setEditable(false);
        lbl5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl5.setText("Información de Contacto: ");
        lbl5.setBorder(null);
        lbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl5ActionPerformed(evt);
            }
        });
        add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        lbl1.setEditable(false);
        lbl1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl1.setText("Nombre del Software: ");
        lbl1.setBorder(null);
        lbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl1ActionPerformed(evt);
            }
        });
        add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lbl2.setEditable(false);
        lbl2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl2.setText("Versión: ");
        lbl2.setBorder(null);
        lbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl2ActionPerformed(evt);
            }
        });
        add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lbl4.setEditable(false);
        lbl4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl4.setText("Créditos:");
        lbl4.setBorder(null);
        lbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl4ActionPerformed(evt);
            }
        });
        add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText(" 1.0.0");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 110, 30));

        lbl7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl7.setText("© Stella. All rights reserved.   ");
        add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 440, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("NoteApp");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 110, 30));

        lbl3.setEditable(false);
        lbl3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl3.setText("Fecha de Lanzamiento:");
        lbl3.setBorder(null);
        lbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl3ActionPerformed(evt);
            }
        });
        add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText(" Stellaapp@gmail.com");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 200, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText(" Agradecimientos especiales al equipo de desarrollo de AppNote");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 530, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText(" 15/04/2024");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void lbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl5ActionPerformed

    private void lbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1ActionPerformed

    private void lbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl2ActionPerformed

    private void lbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl4ActionPerformed

    private void lbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbl1;
    private javax.swing.JTextField lbl2;
    private javax.swing.JTextField lbl3;
    private javax.swing.JTextField lbl4;
    private javax.swing.JTextField lbl5;
    private javax.swing.JLabel lbl7;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
